apiVersion: v2
name: pagopa-functions-template
description: Microservice description
type: application
version: 0.22.0
appVersion: 0.1.10-1-PAGOPA-2017
dependencies:
  - name: microservice-chart
    version: 1.21.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
