apiVersion: v2
name: pagopa-functions-template
description: Microservice description
type: application
version: 0.12.0
appVersion: 0.1.5-1-PAGOPA-1176-remove-deploy-pipeline
dependencies:
  - name: microservice-chart
    version: 1.21.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
